simplementweb_settings:
    resource: '../src/SimplementWeb/SettingsBundle/Controller'
    type:     annotation

simplementweb_history:
    resource: '../src/SimplementWeb/HistoryBundle/Controller'
    type:     annotation
